image: node:10-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - backend/node_modules/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - cd backend
    - npm install

test:
  stage: test
  tags:
    - docker
  script:
    - cd backend
    - npm run ci-test